### ISSUE TITLE
test_teleop: MockArm rot — multiple tests fail with AttributeError after teleop API evolution

### ISSUE THREAD

**Issue by siddhss5** [personalrobotics/mj_manipulator#160]
## Symptom

\`tests/test_teleop.py\` has accumulated 17 failures on \`main\` as \`teleop\` / \`cartesian\` API evolved past what \`MockArm\` covers. The first chain of errors:

1. \`AttributeError: '_Config' object has no attribute 'reactive_gain'\` — added in #157.
2. After adding that: \`AttributeError: 'MockArm' object has no attribute 'get_joint_limits'\`.
3. After adding that: \`AttributeError: '_Config' object has no attribute 'kinematic_limits'\`.
4. After switching the mock config to a real \`ArmConfig\`: \`TypeError: mj_jacSite(): incompatible function arguments\` — \`CartesianController\` now calls \`mujoco.mj_jacSite\` on \`arm.env.model\`, which the mock can't provide without a real \`MjModel\`.

Each layer of the mock has fallen behind a different code path; nudging one attribute reveals the next.

## Impact

CI has been failing on \`main\` since #157, masked by \`gh pr merge --admin\` on subsequent PRs. The 17 failures are all in test_teleop.py; the rest of the suite (~475 tests) passes.

## Affected test classes

All of \`tests/test_teleop.py\`:

- \`TestPoseInput\` (5)
- \`TestIdleTimeout::test_pose_persists_after_timeout\` + \`test_no_idle_with_continuous_input\` (2)
- \`TestInputSwitching::test_pose_clears_twist\` (1)
- \`TestRecording\` (4)
- \`TestSafetyModes\` (5)

\`TestTeleopLifecycle\` (4 tests) still passes — those don't drive \`step()\` past \`activate()\`.

## Recommended fix

Rewrite the tests to use a real menagerie arm + \`Environment.from_model\`. We already do this in \`tests/test_arm.py\` and \`tests/test_mink_solver.py\`. The TeleopController is a thin enough layer that integration-style tests against a real model are cheap and more honest than maintaining MockArm in lockstep with the arm/cartesian API.

Estimated effort: ~half a day. Out of scope for the ssik PR (#159), where these failures surfaced.

## Workaround in #159

Tests in the affected classes are marked \`pytest.skip\` with a link to this issue so #159's CI can be green. Remove the skip markers when this is resolved.
